# -*-coding: utf-8 -*-

MALE = 0      # 男性
FEMALE = 1    # 女性
OTHER = 2     # 其他性别

SEX_LIST = [MALE, FEMALE, OTHER]    # 性别列表


TRANSACTION_TYPE_LEAVE = 0
TRANSACTION_TYPE_RAISE = 1
TRANSACTION_TYPE_REIMBURSEMENT = 2


TRANSACTION_TYPE_LIST = [TRANSACTION_TYPE_LEAVE, TRANSACTION_TYPE_RAISE, TRANSACTION_TYPE_REIMBURSEMENT]


CLUSTER = 'cluster'
BUSINESS = 'business'
ACADEMY = 'academy'

USER_PERMISSION_LIST = [CLUSTER, BUSINESS, ACADEMY]
