# -*-coding: utf-8 -*-

MALE = 1      # 男性
FEMALE = 2    # 女性
OTHER = 3     # 其他性别

SEX_LIST = [MALE, FEMALE, OTHER]    # 性别列表


TRANSACTION_TYPE_LEAVE = 0
TRANSACTION_TYPE_RAISE = 1
TRANSACTION_TYPE_REIMBURSEMENT = 2


TRANSACTION_TYPE_LIST = [TRANSACTION_TYPE_LEAVE, TRANSACTION_TYPE_RAISE, TRANSACTION_TYPE_REIMBURSEMENT]


CLUSTER = 'cluster'
BUSINESS = 'business'
ACADEMY = 'academy'

USER_PERMISSION_LIST = [CLUSTER, BUSINESS, ACADEMY]

USER_STATUS_NORMAL = 1
USER_STATUS_CHECK = 2
USER_STATUS_NOPASS = 3
USER_STATUS_FORBID = 4
USER_STATUS_DELETE = 5

USER_STATUS_LIST = [USER_STATUS_CHECK, USER_STATUS_NORMAL, USER_STATUS_NOPASS, USER_STATUS_FORBID, USER_STATUS_DELETE]

USER_STATUS_DICT = {
    USER_STATUS_NORMAL: u'正常',
    USER_STATUS_CHECK: u'待审核',
    USER_STATUS_NOPASS: u'审核不通过',
    USER_STATUS_FORBID: u'禁用',
    USER_STATUS_DELETE: u'已删除'
}
